[tool.poetry]
name = "nightskycam"
version = "0.0.1"
description = "taking pictures at night"
authors = [
	"Vincent Berenz <vberenz@tuebingen.mpg.de>",
]
packages = [
	 { include = "nightskycam" },
] 

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = [
    "cv2",
]
ignore_missing_imports = true
