frequency =  0.013
nightskycam = "{{ nightskycam }}"
start_time = "20:00"
end_time = "07:00"
use_sun_alt = false
use_weather = false
cloud_cover_threshold = 70
destination_folder = "{{ root_directory }}/process"
AutoExpMaxExpMS = 30000
AutoExpMaxGain = 285
AutoExpTargetBrightness = 100
BandWidth = "auto"
CoolerOn = true
Exposure = 30000000
Flip = 0
Gain = 121
HighSpeedMode = false
MonoBin = false
Offset = 8
TargetTemp = 0
WB_B = 95
WB_R = 52
start_x = 0
start_y = 0
width = 4144
height = 2822
bins = 1
types = "raw16"


# uncomment only if equipped with
# an adapter to set the focus and aperture
#focus = 140
#active_aperture = 441
#inactive_aperture = 2303