frequency = 0.5
command_file = "{{ root_directory }}/commands/commands.toml"
url = "{{ websockets_url }}/updown/commands/{{ nightskycam }}"
password = "{{ command_password}} "

# uncomment if you setup  a certificate file
# (see vars.toml)
# cert_file = "{{ cert_file }}"

# uncomment if you use a shared secret token
# for communication with the server
# token = "{{ token }}"