frequency = 1.0
host = "{{ ftp_host }}"
port = "{{ ftp_port }}"
username = "{{ ftp_username }}"
password = "{{ ftp_password }}"
source_folder = "{{ root_directory }}/ftp"
batch = 4
remote_subdir = ""
nightskycam = "{{ nightskycam }}"
