[main]

period = 2.0
local_log_file = "/opt/nightskycam/logs/logs.txt"

["nightskycam.skythreads.FtpThread"]

host = "127.0.0.1"
port = "2121"
username = "test"
passwd = "12345"
upload_every = 1.0
local_dir = "/opt/nightskycam/ftp"

["nightskycam.skythreads.StatusThread"]

tmp_dir = "/opt/nightskycam/tmp"
final_dir = "/opt/nightskycam/ftp"
update_every = 1.0

["nightskycam.skythreads.ConfigThread"]

url = "http://127.0.0.1:43951"
update_every = 2.0

